apiVersion: v1
kind: Service
metadata:
  name: "%(name)s"
  namespace: "%(namespace)s"
spec:
  selector:
    app: "%(name)s"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
